name: Lacework-UNDeploy CT and Config
# TODO: Leverage Terraform backend maintenance of state file (https://www.terraform.io/docs/language/settings/backends/s3.html)
# Controls when the action will run. 
on:
  repository_dispatch:
    types: [destroy]
  workflow_dispatch:
    inputs:
      AWS_NAME: 
        description: 'This is a fake parameter'
        default: 'who cares, its fake'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  UnDeployLW:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: download Lacework CLI
        run: |
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh -O

      - name: Run lacework installer
        run: |
          sudo chmod +x install.sh
          sudo ./install.sh
          lacework version
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Do the THING
        env:
          LW_API_KEY: ${{ secrets.LW_API_KEY }}
          LW_API_SECRET: ${{ secrets.LW_API_SECRET }}
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
        run: | 
          terraform init
          terraform apply -destroy --auto-approve
